version: 2

models:
  - name: trips
    description: Incremental fact table containing ride transactions.

    columns:
      - name: trip_id
        tests:
          - unique
          - not_null

      - name: customer_id
        tests:
          - not_null

      - name: driver_id
        tests:
          - not_null

      - name: vehicle_id
        tests:
          - not_null

      - name: last_updated_timestamp
        tests:
          - not_null
